### Booking ------------------------------------------------------

# app.use('/api',bookingRoutes);

###

GET http://localhost:3000/api/room  HTTP/1.1


###

POST http://localhost:3000/api/room HTTP/1.1
Content-Type: application/json

{
    "id":"2",
    "username": "test t estt tes", 
    "role": "ttteesssttting ttteesssttting"
}

###

DELETE http://localhost:3000/api/room:23 HTTP/1.1
Content-Type: application/json

### Deployment ------------------------------------------------------
###

GET http://localhost:3000/api/messages  HTTP/1.1


###

GET http://localhost:3000/api/messages:myRandomChatRoomId  HTTP/1.1

###

POST http://localhost:3000/api/messages HTTP/1.1
Content-Type: application/json

{
    "id":"1",
    "parter_deployed_to": "23", 
    "body": "23", 
    "user_id": "23", 
    "status": "23", 
}

###

DELETE http://localhost:3000/api/messages:23 HTTP/1.1
Content-Type: application/json


### User ------------------------------------------------------
###

GET http://localhost:3000/api/users  HTTP/1.1

###

POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "id":"1",
    "username": "23", 
    "role": "ttteesssttting ttteesssttting"
}

###

DELETE http://localhost:3000/api/users:23 HTTP/1.1
Content-Type: application/json



###

POST http://localhost:3000/api/upload:tester HTTP/1.1
Content-Type: application/json

{
    "id":"1",
    "username": "23", 
    "role": "ttteesssttting ttteesssttting"
}

